-- --||Services||--
-- local RS = game:GetService("ReplicatedStorage")
-- local UnvalidatedAssetService = game:GetService("UnvalidatedAssetService")

-- --||Nevermore Shit||--
-- ----------------------------- getting servicebag and loader -----------------------------

-- local NeverMorePackages = RS.Nevermore
-- local loader = NeverMorePackages:FindFirstChild("LoaderUtils", true).Parent
-- local Nevermore = require(loader).bootstrapGame(NeverMorePackages)

-- local ServiceBag = Nevermore("ServiceBag")
-- local serviceBag = ServiceBag.new()

-- ----- ------------------------ START SERVICEBAG -----------------------------
-- serviceBag:Init()
-- serviceBag:Start()

-- _G.Client_ServiceBag = serviceBag

-- require(script.Parent.App)
